ATTRIBUTE_INVENTORY = 'i'
ATTRIBUTE_OPTION = 'o'
ATTRIBUTE_STATEMENT = 's'
ATTRIBUTE_TYPES = (
    (ATTRIBUTE_INVENTORY, 'Inventory'),
    (ATTRIBUTE_OPTION, 'DHCP option'),
    (ATTRIBUTE_STATEMENT, 'DHCP statement'),
)
