ATTRIBUTE_INFORMATIONAL = 'i'
ATTRIBUTE_OPTION = 'o'
ATTRIBUTE_STATEMENT = 's'
ATTRIBUTE_TYPES = (
    (ATTRIBUTE_INFORMATIONAL, 'Informational'),
    (ATTRIBUTE_OPTION, 'DHCP option'),
    (ATTRIBUTE_STATEMENT, 'DHCP statement'),
)
