LEVEL_GUEST = 0
LEVEL_USER = 1
LEVEL_ADMIN = 2

LEVELS = {}
LEVELS[LEVEL_GUEST] = 'Guest'
LEVELS[LEVEL_USER] = 'User'
LEVELS[LEVEL_ADMIN] = 'Admin'

IP_TYPE_4 = '4'
IP_TYPE_6 = '6'
IP_TYPES = {}
IP_TYPES[IP_TYPE_4] = 'ipv4'
IP_TYPES[IP_TYPE_6] = 'ipv6'
